project:
  type: website
  output-dir: docs

website:
  title: "jjf234.github.io"
  navbar:
    right:
      - icon: github
        href: https://github.com/jjf234
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual