project:
  type: website
  output-dir: docs

website:
  title: "jasonjfoster.github.io"
  navbar:
    right:
      - icon: github
        href: https://github.com/jasonjfoster
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: true 