---
title: "Nonlinear nonparametric statistics"
author: "[Jason Foster](mailto:jason.j.foster@gmail.com)"
date: last-modified
categories:
  - analysis
  - finance
  - r
draft: true
editor: 
  mode: source
---

```{r}
factors_r <- c("SP500", "DTWEXAFEGS") # "SP500" does not contain dividends; note: "DTWEXM" discontinued as of Jan 2020
factors_d <- c("DGS10", "BAMLH0A0HYM2")
```

```{r}
risk_sign <- c(SP500 = 1, DTWEXAFEGS = 1, DGS10 = -1, BAMLH0A0HYM2 = -1)
```

```{r}
#| echo: false
#| output: false # Registered S3 method overwritten by 'quantmod': method as.zoo.data.frame from zoo
source("../helper-levels.R")
```

```{r}
#| echo: false
returns_xts <- na.omit(returns_xts)
```

# Ordinary least squares

```{r}
shock <- -0.1
returns_z_xts <- returns_xts[ , "SP500"]
```

```{r}
beta <- solve(t(returns_z_xts) %*% returns_z_xts) %*% (t(returns_z_xts) %*% returns_xts)
implied_shocks <- shock %*% beta * risk_sign
```

```{r}
round(data.frame(
  implied_shocks = t(implied_shocks),
  row.names = c("SP500", "USD", "US10Y", "USHY")
) * 100, 2)
```


# Principal components analysis

```{r}
comp <- 1
```

```{r}
LV <- eigen(cov(returns_xts))
L <- LV[["values"]]
V <- LV[["vectors"]]
scale <- shock / (sqrt(L[comp]) * V[ , comp])[1]
implied_shocks_pc <- scale * (sqrt(L[comp]) * V[ , comp]) * risk_sign
```

```{r}
round(data.frame(
  implied_shocks = t(implied_shocks),
  implied_shocks_pc = implied_shocks_pc,
  row.names = c("SP500", "USD", "US10Y", "USHY")
) * 100, 2)
```

# Nonlinear nonparametric statistics

## Partial moments

-   <https://cran.r-project.org/web/packages/NNS/vignettes/NNSvignette_Partial_Moments.html>

```{r}
sigma <- cov(returns_xts)
```

```{r}
#| output: false
# Registered S3 method overwritten by 'data.table': print.data.table
# Registered S3 methods overwritten by 'htmltools': print.html (from=tools:rstudio), print.shiny.tag (from=tools:rstudio), print.shiny.tag.list (from=tools:rstudio)
# Registered S3 method overwritten by 'htmlwidgets': print.htmlwidget (from=tools:rstudio)
pm <- NNS::PM.matrix(LPM_degree = 1, UPM_degree = 1, target = "mean",
                     variable = returns_xts, pop_adj = TRUE)
```

```{r}
all.equal(sigma, pm$cov.matrix)
```

```{r}
cl_pm <- pm$clpm
cu_pm <- pm$cupm
dl_pm <- pm$dlpm
du_pm <- pm$dupm
```

```{r}
all.equal(sigma, (cl_pm + cu_pm) - (dl_pm + du_pm))
```

## Implied shocks

```{r}
# LV <- eigen(cov(cl_pm - (dl_pm + du_pm)))
# L <- LV[["values"]]
# V <- LV[["vectors"]]
# scale <- shock / (sqrt(L[comp]) * V[ , comp])[1]
# implied_shocks_pm <- scale * (sqrt(L[comp]) * V[ , comp]) * risk_sign

cov_pm <- cov(cl_pm - (dl_pm + du_pm))
cov_z_pm <- cov_pm[1, 1, drop = FALSE]
cov_r_pm <- cov_pm[1, ]

beta <- solve(cov_z_pm, t(cov_r_pm))
implied_shocks_pm <- shock %*% beta * risk_sign
```

```{r}
round(data.frame(
  implied_shocks = t(implied_shocks),
  # implied_shocks_pc = implied_shocks_pc,
  implied_shocks_pm = t(implied_shocks_pm),
  row.names = c("SP500", "USD", "US10Y", "USHY")
) * 100, 2)
```

## Bootstrapping

- <https://github.com/OVVO-Financial/Finance/blob/main/stress_test.md>
- <https://cran.r-project.org/web/packages/NNS/vignettes/NNSvignette_Sampling.html>

```{r}
target <- 0
n_samples <- 1e6
```

```{r}
idx <- which(rowSums(returns_xts > target) != length(factors)) # exclude cupm quadrant
```

```{r}
returns_bs <- apply(returns_xts[idx, ], 2, function(x) {
  result <- NNS::NNS.meboot(as.vector(x),
                            reps = ceiling(n_samples / length(idx)),
                            rho = 1,
                            type = "pearson")["replicates", ]$replicates
  tail(as.vector(result), n_samples)
})
```

```{r}
bs <- NNS::PM.matrix(LPM_degree = 1, UPM_degree = 1, target = "mean",
                     variable = returns_bs, pop_adj = TRUE)
```

```{r}
cl_bs <- bs$clpm
cu_bs <- bs$cupm
dl_bs <- bs$dlpm
du_bs <- bs$dupm
```

```{r}
# # LV <- eigen(cov(returns_bs))
# LV <- eigen(cov(cl_pm - (dl_pm + du_pm)))
# L <- LV[["values"]]
# V <- LV[["vectors"]]
# scale <- shock / (sqrt(L[comp]) * V[ , comp])[1]
# implied_shocks_bs <- scale * (sqrt(L[comp]) * V[ , comp]) * risk_sign

cov_bs <- cov(cl_bs - (dl_bs + du_bs))
cov_z_bs <- cov_bs[1, 1, drop = FALSE]
cov_r_bs <- cov_bs[1, ]

beta <- solve(cov_z_bs, t(cov_r_bs))
implied_shocks_bs <- shock %*% beta * risk_sign
```

```{r}
round(data.frame(
  implied_shocks = t(implied_shocks),
  # implied_shocks_pc = implied_shocks_pc,
  implied_shocks_pm = t(implied_shocks_pm),
  implied_shocks_bs = t(implied_shocks_bs),
  row.names = c("SP500", "USD", "US10Y", "USHY")
) * 100, 2)
```