---
title: "Software development"
author: "[Jason Foster](mailto:jason.j.foster@gmail.com)"
date: today
categories:
  - software
  - development
execute:
  eval: false
---

# System setup

```         
# environment variable: PATH=c:\rtools40\usr\bin
```

# Git and GitHub

```         
git config --global user.name "<NAME>"
git config --global user.email "<EMAIL>"
```

If needed, generate an SSH key: RStudio \> Tools \> Git/SVN \> Create RSA Key...
Then give GitHub your SSH public key: GitHub \> SSH and GPG Keys \> New SSH key

```
# ...or create a new repository on the command line
echo "# <REPO>" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:<OWNER>/<REPO>.git
git push -u origin main
```

```
# ...or push an existing repository from the command line
git remote add origin git@github.com:<OWNER>/<REPO>.git
git branch -M main
git push -u origin main
```

```         
# git remote set-url origin git@github.com:<OWNER>/<REPO>.git
```

# Development workflow

```{r}
RcppArmadillo::RcppArmadillo.package.skeleton(name = "anRpackage",
                                              path = ".",
                                              example_code = FALSE)
```

# Compiled code

```{r}
Rcpp::compileAttributes(verbose = TRUE)
tools::package_native_routine_registration_skeleton(".", character_only = FALSE)
```

# Object documentation

```{r}
roxygen2::roxygenize()
```

# Automated checking

```{r}
usethis::use_github_action("check-standard")
usethis::use_github_action("test-coverage")
```
